from __future__ import annotations

PROFILE_PRESETS = {
    "widescreen": {
        "pixel_width": 1920,
        "pixel_height": 1080,
        "frame_width": 16.0,
        "frame_height": 9.0,
        "frame_rate": 60,
    },
    "shorts": {
        "pixel_width": 1080,
        "pixel_height": 1920,
        "frame_width": 9.0,
        "frame_height": 16.0,
        "frame_rate": 60,
    },
}

SCENE_LAYOUTS = {
    "single_packet": {
        "widescreen": {
            "x_range": (-6.2, 6.2),
            "y_range": (-4.0, 4.0),
            "surface_resolution": (34, 24),
            "plane_resolution": (18, 14),
            "camera_phi": 68.0,
            "camera_theta": -40.0,
            "camera_zoom": 1.05,
            "frame_center": (0.0, 0.2, -0.35),
            "top_buff": 0.16,
            "title_scale": 0.58,
            "formula_scale": 0.42,
            "label_scale": 0.44,
            "note_scale": 0.40,
            "field_z_scale": 1.05,
        },
        "shorts": {
            "x_range": (-4.4, 4.4),
            "y_range": (-4.8, 4.8),
            "surface_resolution": (28, 32),
            "plane_resolution": (14, 18),
            "camera_phi": 70.0,
            "camera_theta": -36.0,
            "camera_zoom": 1.08,
            "frame_center": (0.0, 0.95, -0.30),
            "top_buff": 0.18,
            "title_scale": 0.60,
            "formula_scale": 0.45,
            "label_scale": 0.48,
            "note_scale": 0.44,
            "field_z_scale": 1.10,
        },
    },
    "two_packets": {
        "widescreen": {
            "x_range": (-6.8, 6.8),
            "y_range": (-4.0, 4.0),
            "surface_resolution": (34, 24),
            "plane_resolution": (18, 14),
            "camera_phi": 68.0,
            "camera_theta": -41.0,
            "camera_zoom": 1.04,
            "frame_center": (0.0, 0.15, -0.35),
            "top_buff": 0.16,
            "title_scale": 0.58,
            "formula_scale": 0.42,
            "label_scale": 0.44,
            "note_scale": 0.40,
            "field_z_scale": 1.00,
        },
        "shorts": {
            "x_range": (-4.9, 4.9),
            "y_range": (-5.2, 5.2),
            "surface_resolution": (28, 34),
            "plane_resolution": (14, 20),
            "camera_phi": 70.0,
            "camera_theta": -36.0,
            "camera_zoom": 1.08,
            "frame_center": (0.0, 1.0, -0.28),
            "top_buff": 0.18,
            "title_scale": 0.60,
            "formula_scale": 0.45,
            "label_scale": 0.48,
            "note_scale": 0.44,
            "field_z_scale": 1.06,
        },
    },
    "mediator": {
        "widescreen": {
            "x_range": (-6.8, 6.8),
            "y_range": (-4.4, 4.4),
            "surface_resolution": (32, 24),
            "plane_resolution": (18, 14),
            "camera_phi": 74.0,
            "camera_theta": -58.0,
            "camera_zoom": 0.92,
            "frame_center": (0.0, -0.10, 0.78),
            "top_buff": 0.14,
            "title_scale": 0.56,
            "formula_scale": 0.39,
            "label_scale": 0.42,
            "note_scale": 0.38,
            "field_z_scale": 0.92,
            "phi_target_height": 1.05,
            "chi_target_height": 0.95,
            "phi_visual_gain": 1.0,
            "chi_visual_gain": 1.0,
            "mediator_shift": 2.05,
            "show_a0_surface": True,
            "show_charge_centers": False,
            "playback_time_scale": 1.0,
        },
        "shorts": {
            "x_range": (-4.9, 4.9),
            "y_range": (-5.0, 5.0),
            "surface_resolution": (26, 30),
            "plane_resolution": (14, 18),
            "camera_phi": 75.0,
            "camera_theta": -52.0,
            "camera_zoom": 0.95,
            "frame_center": (0.0, 0.72, 0.92),
            "top_buff": 0.16,
            "title_scale": 0.58,
            "formula_scale": 0.42,
            "label_scale": 0.46,
            "note_scale": 0.42,
            "field_z_scale": 0.94,
            "phi_target_height": 1.15,
            "chi_target_height": 1.00,
            "phi_visual_gain": 1.0,
            "chi_visual_gain": 1.0,
            "mediator_shift": 2.20,
            "show_a0_surface": True,
            "show_charge_centers": False,
            "playback_time_scale": 1.0,
        },
    },
    "scalar_qed": {
        "widescreen": {
            "surface_resolution": (34, 26),
            "plane_resolution": (18, 14),
            "camera_phi": 74.0,
            "camera_theta": -57.0,
            "camera_zoom": 0.93,
            "frame_center": (0.0, -0.08, 0.78),
            "top_buff": 0.14,
            "title_scale": 0.56,
            "formula_scale": 0.39,
            "label_scale": 0.42,
            "note_scale": 0.38,
        },
        "shorts": {
            "surface_resolution": (28, 32),
            "plane_resolution": (14, 18),
            "camera_phi": 75.0,
            "camera_theta": -52.0,
            "camera_zoom": 0.95,
            "frame_center": (0.0, 0.74, 0.92),
            "top_buff": 0.16,
            "title_scale": 0.58,
            "formula_scale": 0.42,
            "label_scale": 0.46,
            "note_scale": 0.42,
        },
    },
}


def get_profile_preset(profile: str) -> dict:
    return PROFILE_PRESETS[profile]


def get_scene_layout(scene_key: str, profile: str) -> dict:
    return dict(SCENE_LAYOUTS[scene_key][profile])
